### PR TITLE
Added C-style pointers

### PR DESCRIPTION
**Pull request by lucasnorman07**
Added C-style pointer types, the "address of" operator and the "pointer dereference" operator. Also started stracking custom type data for each AST node and variable.

### CODE REVIEW

**Comment by pontushenriksson** [comment]
Is this ready to be merged? :)

**Comment by lucasnorman07** [comment]
It depends on how we decide to handle pointer syntax. This only implements C-style pointers, but if we want another syntax I can also add that in another PR.

**Comment by pontushenriksson** [comment]
Okay. I will leave this open for a little bit longer then so no other PR needs to be opened.

**Comment by lucasnorman07** [comment]
This can be merged now, because we are going to use C-style pointer syntax, and then add references as a complement to pointers in the future, as a more elegant and safe approach.

**Review by pontushenriksson — APPROVED** [review]
Looks great! Merging now.

**Pull request merged**
